/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.frejt.piet.controller;

import java.nio.file.Path;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.frejt.piet.entity.Board;
import com.frejt.piet.exception.PietExecutionException;
import com.frejt.piet.utils.reader.PietFileReader;

public class Interpreter {

    private static final Logger log = LogManager.getLogger(Interpreter.class);
    
    /**
     * Entry point to the program.
     * 
     * @param args: args[0] - String holding the image's file path
     */
    public static void main(String[] args) {

        Path runFile = InterpreterUtils.getRunFile(args);
        log.debug("Running file " + runFile.toString());

        PietFileReader fileReader = new PietFileReader(runFile);

        try {
            Board board = fileReader.convertFileToBoard();
            BoardRunner.runBoard(board);
            
        } catch (PietExecutionException e) {
            log.error("Board was unable to be read: " + e.getMessage());
        }
    }
}

/**
 * Thank you, Larry Tesler.
 * 
 * Realized that ^ may sound like I was copy+pasting from outside sources, I
 * wasn't.
 * 
 * Some of the code (converting numbers -> colors) was repetitive, where I
 * duplicated a lot of code.
 * 
 * Larry Tesler was the creator of the copy & paste commands, according to
 * Wikipedia.
 * 
 * All of this code was written by myself (Trent Freeman), and no code was taken
 * from any outside sources.
 * 
 * 
 * Also shout of to Sean Szumlanski, a (former) CS professor at UCF.
 * 
 * He initially introduced me to Piet and got me interested in writing this
 * program, which has taken up a large chunk of time (which I've mostly
 * enjoyed).
 */